//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhapKho
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public string masp { get; set; }
        public string tensp { get; set; }
        public string dmuc { get; set; }
        public Nullable<int> sluong { get; set; }
        public Nullable<double> dgia { get; set; }
        public string kho { get; set; }
        public Nullable<System.DateTime> ngaynhap { get; set; }
        public Nullable<double> ttien { get; set; }
    }
}
