//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuCungEntityFramwork
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuCung
    {
        public string MaDon { get; set; }
        public string TenThuCung { get; set; }
        public string ChungLoai { get; set; }
        public Nullable<int> CanNang { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
        public string TinhTrang { get; set; }
        public string DichVu { get; set; }
        public Nullable<double> ChiPhiThuoc { get; set; }
        public Nullable<double> SoNgay { get; set; }
        public Nullable<double> Tong { get; set; }
    }
}
